---

- name: destroy/aws | destroy vms
  block:
    - name: destroy/aws | Remove instances termination protection
      amazon.aws.ec2_instance:
        access_key: "{{cluster_vars[buildenv].aws_access_key | default(omit)}}"
        secret_key: "{{cluster_vars[buildenv].aws_secret_key | default(omit)}}"
        session_token: "{{cluster_vars[buildenv].aws_session_token | default(omit)}}"
        region: "{{ cluster_vars.region }}"
        state: "{{ item.instance_state }}"
        termination_protection: false
        instance_ids: ["{{ item.instance_id }}"]
      with_items: "{{ hosts_to_destroy | json_query(\"[].{instance_id:instance_id, instance_state: instance_state}\") | default([]) }}"

    - name: destroy/aws | Destroy VMs
      amazon.aws.ec2_instance:
        access_key: "{{cluster_vars[buildenv].aws_access_key | default(omit)}}"
        secret_key: "{{cluster_vars[buildenv].aws_secret_key | default(omit)}}"
        session_token: "{{cluster_vars[buildenv].aws_session_token | default(omit)}}"
        region: "{{ cluster_vars.region }}"
        state: "absent"
        instance_ids: "{{ hosts_to_destroy | json_query(\"[].instance_id\") }}"
        wait: true

    - name: destroy/aws | Get any attached Elastic IPs
      amazon.aws.ec2_eip_info:
        access_key: "{{cluster_vars[buildenv].aws_access_key | default(omit)}}"
        secret_key: "{{cluster_vars[buildenv].aws_secret_key | default(omit)}}"
        session_token: "{{cluster_vars[buildenv].aws_session_token | default(omit)}}"
        region: "{{ cluster_vars.region }}"
        filters:
          public-ip: "{{ hosts_to_destroy | json_query(\"[].ipv4.public\") | default([]) }}"
      register: r__ec2_eip_info

    - name: destroy/aws | r__ec2_eip_info
      debug: msg={{r__ec2_eip_info}}

    - name: destroy/aws | Delete Elastic IPs (if any were found)
      amazon.aws.ec2_eip:
        access_key: "{{cluster_vars[buildenv].aws_access_key | default(omit)}}"
        secret_key: "{{cluster_vars[buildenv].aws_secret_key | default(omit)}}"
        session_token: "{{cluster_vars[buildenv].aws_session_token | default(omit)}}"
        region: "{{ cluster_vars.region }}"
        ip: "{{ item.public_ip }}"
        state: absent
      with_items: "{{ r__ec2_eip_info.addresses }}"
  when: hosts_to_destroy | length > 0


- name: destroy/aws | destroy networking (when '-e destroy_lifecycle=_all_')
  block:
    - name: destroy/aws | Delete security group
      amazon.aws.ec2_security_group:
        access_key: "{{cluster_vars[buildenv].aws_access_key | default(omit)}}"
        secret_key: "{{cluster_vars[buildenv].aws_secret_key | default(omit)}}"
        session_token: "{{cluster_vars[buildenv].aws_session_token | default(omit)}}"
        region: "{{cluster_vars.region}}"
        name: "{{ cluster_name }}-sg"
        state: absent
  when: destroy_lifecycle is defined and destroy_lifecycle == '_all_'
