---

- name: destroy | get_cluster_hosts_state
  include_role:
    name: "clusterverse.clusterverse.cluster_hosts"
    tasks_from: "get_cluster_hosts_state.yml"

- name: destroy | destroy the cluster of VMs
  block:
    - name: destroy | debug destroy_lifecycle
      debug: msg={{destroy_lifecycle}}
      when: destroy_lifecycle is defined

    - name: destroy | debug hosts_to_destroy_override
      debug: msg={{hosts_to_destroy_override}}
      when: hosts_to_destroy_override is defined

    - name: destroy | debug hosts_to_destroy
      debug: msg={{hosts_to_destroy}}

    - name: destroy | Delete DNS
      include_tasks: dns.yml
      when: (cluster_vars.dns_server is truthy) and (cluster_vars.dns_nameserver_zone is truthy)

    - name: destroy | Destroy VMs (and attached networking, IPs, etc - cloud-dependent)
      include_tasks: "{{cluster_vars.cloud_type}}.yml"
  vars:
    _hosts_to_destroy_by_lifecycle_state: "{{cluster_hosts_state if destroy_lifecycle == '_all_' else cluster_hosts_state | json_query('[?tagslabels.cv__lifecycle_state==`' + destroy_lifecycle + '`]') | default(omit) }}"
    hosts_to_destroy: "{{ hosts_to_destroy_override | default(_hosts_to_destroy_by_lifecycle_state) }}"

- name: destroy | Re-acquire the dynamic inventory (includes cluster_hosts_state).  Should cause inventory to be truncated/emptied.
  include_role:
    name: clusterverse.clusterverse.dynamic_inventory

- name: destroy | Re-acquire the cluster_hosts_target as a destroy_lifecycle=_all_ will change the cluster_suffix
  include_role:
    name: clusterverse.clusterverse.cluster_hosts
    tasks_from: "get_cluster_hosts_target.yml"
  when: destroy_lifecycle is defined and destroy_lifecycle == '_all_'
