---

- name: _scheme_addnewvm_rmdisk_rollback/by_hosttype | Debug canary type
  debug: msg="Canary redeploy ({{canary}}) selected"


- name: _scheme_addnewvm_rmdisk_rollback/by_hosttype | Run redeploy per host.  Delete one at a time, then reprovision.
  include_tasks: redeploy_by_hosttype_by_host.yml
  with_items: >-
    {%- if canary is defined and canary == "start" -%}
    {{ (cluster_hosts_target_by_hosttype[hosttype] | sort(attribute='hostname'))[:1] }}
    {%- elif canary is defined and canary == "finish" -%}
    {{ (cluster_hosts_target_by_hosttype[hosttype] | sort(attribute='hostname'))[1:] }}
    {%- elif canary is defined and canary == "filter" -%}
    {{ (cluster_hosts_target_by_hosttype[hosttype] | sort(attribute='hostname') | selectattr('hostname', 'search', canary_filter_regex) | list) }}
    {%- elif canary is defined and canary == "none" -%}
    {{ (cluster_hosts_target_by_hosttype[hosttype] | sort(attribute='hostname')) }}
    {%- else -%}
    {{ [] }}
    {%- endif -%}
  loop_control: { loop_var: cluster_host_redeploying }
