namespace: clusterverse
name: clusterverse
version: 0.0.0       # This is automatically filled by Jenkins on galaxy release with the current git release tag number.
readme: README.md
authors:
  - Dougal Seeley (@dseeley)
description: Full-lifecycle cloud infrastructure cluster management
license:
  - BSD-3-Clause

tags: ['cluster', 'management', 'aws', 'gcp', 'azure', 'libvirt', 'system']

dependencies:
  dseeley.blockdevmap: ">=1.0.14,<2.0.0"
  dseeley.nested_playbook: ">=1.0.0,<2.0.0"
  dseeley.inventory_lookup: ">=1.0.0,<2.0.0"
  dseeley.esxifree_guest: ">=1.0.12,<2.0.0"
  dseeley.libvirt: ">=2.0.1,<3.0.0"

repository: https://github.com/clusterverse/clusterverse
documentation: https://github.com/clusterverse/clusterverse/blob/master/README.md
homepage: https://github.com/clusterverse/clusterverse
issues: https://github.com/clusterverse/clusterverse/issues
build_ignore: ['.idea', 'jenkinsfiles', '.gitignore', 'Dockerfile*', '*clusterverse-*.tar.gz']
