---

- name: clusterverse | Deploy the cluster
  hosts: localhost
  gather_facts: false
  tasks:
    - assert: { that: "['clusterverse.clusterverse', 'dseeley.tasks_serial', 'dseeley.ansible_vault_pipe'] is subset(galaxy_collections.keys())", success_msg: "clusterverse collections dependencies are met" fail_msg: "Please ensure the clusterverse collections are installed: ansible-galaxy install -r requirements.yml)" }
      vars: { galaxy_collections: "{{lookup('pipe', 'ansible-galaxy collection list --format=json', errors='ignore') | from_json | json_query('*') | combine }}" }
      tags: ["always"]

    - { include_role: { name: "clusterverse.clusterverse.clean", apply: { tags: ["clusterverse_clean"]} }, tags: ["clusterverse_clean"], when: "clean is defined" }
    - { include_role: { name: "clusterverse.clusterverse.create", apply: { tags: ["clusterverse_create"]} }, tags: ["clusterverse_create"] }
    - { include_role: { name: "clusterverse.clusterverse.dynamic_inventory", apply: { tags: ["always"]} }, tags: ["always"] }

- name: clusterverse | Install Ansible-supported python version on old (xenial (16), bionic (18)) machines
  hosts: all:!not_target_hosts
  gather_facts: false
  tags: ["clusterverse_create"]
  tasks:
    - name: "Install python 3.9 from source.  WARNING: This is not the native Python for this OS - things written for Python may not work!"
      raw: |-
        set -euxo pipefail
        while fuser /var/lib/apt/lists/lock -v 2>&1; do sleep 5; done;
        while fuser /var/lib/dpkg/lock -v 2>&1; do sleep 5; done;
        while fuser /var/lib/dpkg/lock-frontend -v 2>&1; do sleep 5; done;
        sudo apt update
        sudo apt install -y build-essential zlib1g-dev libncurses5-dev libgdbm-dev libnss3-dev libssl-dev libreadline-dev libffi-dev wget libapt-pkg-dev
        wget https://www.python.org/ftp/python/3.9.24/Python-3.9.24.tgz --output-document=Python-3.9.24.tgz
        tar xzf Python-3.9.24.tgz
        cd Python-3.9.24/
        sudo ./configure
        sudo make altinstall
        sudo ln -sf /usr/local/bin/python3.9 /usr/bin/python3 
        sudo apt remove -y python3-commandnotfound python3-debian
        curl https://bootstrap.pypa.io/pip/get-pip.py | sudo python3.9
        sudo sed -i '/deb-src/s/^# //' /etc/apt/sources.list
        sudo apt update
        apt-get source python-apt --allow-insecure-repositories || apt-get source python-apt --allow-unauthenticated
        cd python-apt-*
        sudo python3 setup.py install
      register: r__raw__python_install
      until: r__raw__python_install is success
      retries: 2
      delay: 30
      vars:
        ansible_ssh_retries: 10
      when: hostvars['localhost']['cluster_vars']['image'] | regex_search('16[\._]?04|xenial|18[\._]?04|bionic') is truthy


- name: clusterverse | Configure the cluster
  hosts: all:!not_target_hosts
  gather_facts: false
  tasks:
    - { wait_for_connection: "", timeout: 300, tags: ["always"] }
    - { include_role: { name: "clusterverse.clusterverse.config", apply: { tags: ["clusterverse_config"]} }, tags: ["clusterverse_config"] }


###### Application roles
- name: Application roles
  hosts: all:!not_target_hosts
  tasks:
    - { include_role: { name: "clusterverse.clusterverse._dependencies", apply: { tags: ["always"] } }, tags: ["always"], when: "'clusterverse_config' not in ansible_run_tags" }      # If we --skip-tags=clusterverse_config, this will ensure the variables from /cluster_defs are loaded.
    - { include_role: { name: "testrole", apply: { tags: ["testrole"]} }, tags: ["testrole"] }
######


- name: clusterverse | Perform cluster readiness operations
  hosts: localhost
  tasks: [ { include_role: { name: "clusterverse.clusterverse.readiness", apply: { tags: ["clusterverse_readiness"]} }, tags: ["clusterverse_readiness"] } ]
