---

- name: clusterverse | Deploy (and/or delete) the cluster VMs
  hosts: localhost
  gather_facts: false
  tasks:
    - assert: { that: "['clusterverse.clusterverse', 'dseeley.tasks_serial', 'dseeley.ansible_vault_pipe'] is subset(galaxy_collections.keys())", success_msg: "clusterverse collections dependencies are met", fail_msg: "Please ensure the clusterverse collections are installed: ansible-galaxy install -r requirements.yml)" }
      vars: { galaxy_collections: "{{lookup('pipe', 'ansible-galaxy collection list --format=json', errors='ignore') | from_json | json_query('*') | combine }}" }
      tags: ["always"]

    - { include_role: { name: "clusterverse.clusterverse.clean", apply: { tags: ["clusterverse_clean"]} }, tags: ["clusterverse_clean"], when: "clean is defined" }
    - { include_role: { name: "clusterverse.clusterverse.create", apply: { tags: ["clusterverse_create"]} }, tags: ["clusterverse_create"] }
    - { include_role: { name: "clusterverse.clusterverse.dynamic_inventory", apply: { tags: ["always"]} }, tags: ["always"] }

- name: clusterverse | Validate remote python version is supported by local ansible version; import_playbook 'raw_python39_install.yml' if not
  hosts: all:!not_target_hosts
  gather_facts: false
  tags: ["clusterverse_create"]
  tasks:
    - { ansible.builtin.setup: { gather_subset: ["python"] }, ignore_errors: true, register: r__setup__python_version_check }
    - { include_role: { name: "clusterverse.clusterverse.config", tasks_from: "raw_python39_install.yml" }, when: r__setup__python_version_check.failed is defined and r__setup__python_version_check.failed }

- name: clusterverse | Configure the cluster VM OSs (excluding not-being-redeployed hosts)
  hosts: all:!not_target_hosts
  gather_facts: false
  tasks:
    - { wait_for_connection: "", timeout: 300, tags: ["always"] }
    - { include_role: { name: "clusterverse.clusterverse.config", apply: { tags: ["clusterverse_config"]} }, tags: ["clusterverse_config"] }


###### Application roles ######
- name: application | load clusterverse dependencies (if excluded due to --skips-tags)
  hosts: all
  tasks:
    - { include_role: { name: "clusterverse.clusterverse._dependencies", apply: { tags: ["always"] } }, tags: ["always"], when: "'clusterverse_config' not in ansible_run_tags" }      # If we --skip-tags=clusterverse_config, this will ensure the variables from /cluster_defs are loaded.
    - { include_role: { name: "clusterverse.clusterverse.cluster_hosts", apply: { tags: ["always"] } }, tags: ["always"], when: "'clusterverse_create' not in ansible_run_tags" }      # If we --skip-tags=clusterverse_create, this will ensure cluster_suffix is defined.

- name: application | test roles
  hosts: all
  tasks:
    - { include_role: { name: "testrole", apply: { tags: ["testrole"]} }, tags: ["testrole"] }
###### Application roles ######


- name: clusterverse | Perform cluster readiness operations - host (reenable apt services) and DNS/CNAMEs (CNAMES are used for intra-cluster connections, so we don't want to swap them until they're fully built (during redeploy))
  hosts: localhost
  tasks:
    - { include_role: { name: "clusterverse.clusterverse.readiness", tasks_from: "host_readiness.yml" } }
    - { include_role: { name: "clusterverse.clusterverse.readiness", tasks_from: "dns_cname_readiness.yml", apply: { tags: ["clusterverse_readiness"]} }, tags: ["clusterverse_readiness"] }

