---

- name: clusterverse/redeploy | Redeploy the cluster
  hosts: localhost
  gather_facts: false
  tasks:
    - assert: { that: "['clusterverse.clusterverse', 'dseeley.tasks_serial', 'dseeley.ansible_vault_pipe'] is subset(galaxy_collections.keys())", success_msg: "clusterverse collections dependencies are met", fail_msg: "Please ensure the clusterverse collections are installed: ansible-galaxy install -r requirements.yml)" }
      vars: { galaxy_collections: "{{lookup('pipe', 'ansible-galaxy collection list --format=json', errors='ignore') | from_json | json_query('*') | combine }}" }

    - name: clusterverse/redeploy | Run redeploy
      include_role: { name: clusterverse.clusterverse.redeploy }
      vars:
        deployplaybook: "deploy.yml"
        predeleterole: "testrole/_redeploy"
        redeploy_extra_vars:
          k1: "v1"
          dict: { "dict_k1": "dict_v1", "dict_k2": "dict_v2" }
          list: [ "list_v1", "list_v2" ]


###### Application roles (optional) ######
- name: clusterverse/redeploy/application | Application roles
  hosts: all
  tasks:
    - { include_role: { name: "testrole", apply: { tags: ["testrole"]} }, tags: ["testrole"] }
###### Application roles (optional) ######


- name: clusterverse/redeploy | clusterverse.readiness/clean_tmp
  hosts: localhost
  gather_facts: false
  tasks: [ { include_role: { name: "clusterverse.clusterverse.readiness", tasks_from: "clean_tmp.yml"}} ]
