---

- name: set hosts_to_del if canary==start
  set_fact: hosts_to_del={{(cluster_hosts_state_by_hosttype[hosttype] | sort(attribute='name'))[:1]}}
  when: (canary is defined and canary=="start")

- name: set hosts_to_del if canary==finish
  set_fact: hosts_to_del={{(cluster_hosts_state_by_hosttype[hosttype] | sort(attribute='name'))[1:]}}
  when: (canary is defined and canary=="finish")

- name: set hosts_to_del if canary==filter
  set_fact: hosts_to_del={{(cluster_hosts_state_by_hosttype[hosttype] | sort(attribute='name')) | selectattr('name', 'search', canary_filter_regex) | list}}
  when: (canary is defined and canary=="filter")

- name: set hosts_to_del if canary==none
  set_fact: hosts_to_del={{(cluster_hosts_state_by_hosttype[hosttype] | sort(attribute='name'))}}
  when: (canary is defined and canary=="none")

- debug: msg="Canary redeploy ({{canary}}) selected; deleting and redeploying [{{hosts_to_del | json_query('[].name') | join(', ')}}]"
  when: (canary is defined)


- name: Run redeploy per host.  Delete one at a time, then reprovision.
  include_tasks: by_hosttype_by_host.yml
  with_items: "{{ hosts_to_del }}"
  loop_control:
    loop_var: host_to_del
