---

- name: config/ntp | Check whether timedatectl is already syncing with a preinstalled ntp client (if timedatectl fails probably an old version <=18.04 of timedatectl, just install chrony)
  become: true
  command: "timedatectl show --property=NTP --value"
  ignore_errors: true
  register: r__command__timedatectl_show

- name: config/ntp | "debug 'timedatectl show --property=NTP --value'"
  debug: msg="{{r__command__timedatectl_show}}"

- name: config/ntp | Install chrony (if chrony_install is true AND an NTP provider is not already installed)
  block:
    - name: config/ntp | Ubuntu install
      become: true
      apt:
        name: chrony
        update_cache: true
        state: present
      when: ansible_facts['os_family'] == "Debian"

    - name: config/ntp | CentOS install
      become: true
      yum:
        name: chrony
        state: present
      when: ansible_facts['os_family'] == "RedHat"
  when: chrony_install|bool  and  r__command__timedatectl_show.stdout != "yes"
