---

- name: config/pkgs | To ensure the apt we run in clusterverse isn't blocked by background updates, we disable unattended-upgrade and apt-daily timers and wait for in-flight updates to finish.
  block:
    - name: config | Disable unattended-upgrades and apt-daily timers so that packages can be installed
      become: true
      ansible.builtin.systemd_service:
        name: "{{ item }}"
        enabled: false
        state: stopped
        daemon_reload: true
      register: r__systemd__disable_apt_services
      loop:
        - 'apt-daily.timer'
        - 'apt-daily.service'
        - 'apt-daily-upgrade.timer'
        - 'apt-daily-upgrade.service'
        - 'unattended-upgrades.service'
      retries: 10
      delay: 3
      until: r__systemd__disable_apt_services is success
      ignore_errors: true  # Don't fail if the service doesn't stop/disable

    - name: config | Save systemd__disable_apt_services so we can use it to reenable in final readiness play
      set_fact: { systemd__disable_apt_services: "{{r__systemd__disable_apt_services.results}}", cacheable: true }

    - name: config | Wait for in-flight updates to finish, so that apt we run in clusterverse isn't blocked by background updates
      become: true
      shell: "while fuser {{ item }} -v 2>&1; do sleep 5; done;"
      loop:
        - /var/lib/apt/lists/lock
        - /var/lib/dpkg/lock
        - /var/lib/dpkg/lock-frontend
  when: ansible_facts['os_family'] == 'Debian'

- name: config/pkgs | ensure xfsprogs is installed if any of the auto_volumes use xfs
  become: true
  ansible.builtin.apt:
    name: ['xfsprogs']
    update_cache: true
  when: ansible_facts['os_family'] == 'Debian' and xfs_in_auto_volumes
  vars:
    xfs_in_auto_volumes: "{{ cluster_vars | json_query(\"*.hosttype_vars | [0].*.auto_volumes[] | [?fstype==`xfs`] \") | length > 0 }}"

- name: config/pkgs | remove fwupd
  become: true
  ansible.builtin.apt:
    name: ['fwupd']
    state: absent
    allow_change_held_packages: true
    autoremove: true
    purge: true
  when: ansible_facts['os_family'] == 'Debian'

- name: config/pkgs | remove modemmanager
  become: true
  ansible.builtin.apt:
    name: ['modemmanager']
    state: absent
    allow_change_held_packages: true
    autoremove: true
    purge: true
  when: ansible_facts['os_family'] == 'Debian'

- name: confin/pkgs | remove snapd
  block:
    - name: config/pkgs | remove snapd
      become: true
      ansible.builtin.apt:
        name: ['snapd']
        state: absent
        allow_change_held_packages: true
        autoremove: true
        purge: true
      register: r__apt_remove_snapd

# Note: Doesn't work on Unbuntu 16.04
#    - name: config/pkgs | prevent snapd installing with apt upgrade
#      become: true
#      ansible.builtin.dpkg_selections:
#        name: snapd
#        selection: hold

    - name: config/pkgs | prevent snapd installing with apt upgrade
      become: true
      ansible.builtin.shell: apt-mark hold snapd
      when: r__apt_remove_snapd.changed
  when: ansible_facts['os_family'] == 'Debian' and (remove_snapd is defined and remove_snapd|bool)

- name: config/pkgs | reboot if necessary, (following any cloud-init apt upgrades)
  become: true
  block:
    - name: config/pkgs | check if reboot is required (Debian/Ubuntu)
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_required_file
      when: ansible_facts['os_family'] == 'Debian'

    - name: config/pkgs | check if reboot is required (RedHat/CentOS)
      ansible.builtin.command: needs-restarting -r
      register: needs_restarting_result
      failed_when: needs_restarting_result.rc > 1
      changed_when: false
      when: ansible_facts['os_family'] == 'RedHat'

    - name: config/pkgs | reboot and wait if necessary
      ansible.builtin.reboot:
        pre_reboot_delay: 60    # Minimum is 60s (it is converted to minutes).  This is needed so that the module can exit before the VM closes the connection, otherwise (https://github.com/ansible/ansible/issues/47647) occurs.  Symptom is seeing a '255' exit code for the shutdown command, and an exit of "Control master terminated unexpectedly" (it should exit with code 0, and "Received exit status from master 0").
      timeout: 300
      when: (ansible_facts['os_family'] == 'Debian' and reboot_required_file.stat.exists | default(false)) or (ansible_facts['os_family'] == 'RedHat' and needs_restarting_result.rc | default(0) == 1)
  when: update_os is defined and update_os|bool
