---

- name: _scheme_noredeploy_scale_in_only/by_hosttype | Debug canary type
  debug: msg="Canary redeploy ({{canary}}) selected"


- name: _scheme_noredeploy_scale_in_only/by_hosttype | Run redeploy per host.  Stop one at a time.
  include_tasks: redeploy_by_hosttype_by_host.yml
  with_items: >-
    {%- if canary is defined and canary == "start" -%}
    {{ (cluster_hosts_state_by_hosttype[hosttype] | sort(attribute='name'))[:1] }}
    {%- elif canary is defined and canary == "finish" -%}
    {{ (cluster_hosts_state_by_hosttype[hosttype] | sort(attribute='name'))[1:] }}
    {%- elif canary is defined and canary == "filter" -%}
    {{ (cluster_hosts_state_by_hosttype[hosttype] | sort(attribute='name') | selectattr('name', 'search', canary_filter_regex) | list) }}
    {%- elif canary is defined and canary == "none" -%}
    {{ (cluster_hosts_state_by_hosttype[hosttype] | sort(attribute='name')) }}
    {%- else -%}
    {{ [] }}
    {%- endif -%}
  loop_control: { loop_var: host_to_del }